const Map<String, String> ar = {
  // ── General ─────────────────────────────────────────────
  'app_name': 'أمازونات',
  'ok': 'حسناً',
  'cancel': 'إلغاء',
  'retry': 'إعادة المحاولة',
  'save': 'حفظ',
  'delete': 'حذف',
  'edit': 'تعديل',
  'search': 'بحث',
  'see_all': 'عرض الكل',
  'continue_text': 'متابعة',
  'loading': 'جاري التحميل...',
  'no_data': 'لا توجد بيانات',
  'error': 'حدث خطأ ما',
  'success': 'تمت العملية بنجاح',

  // ── Auth / Login ────────────────────────────────────────
  'login_title': 'مرحباً بعودتك',
  'login_subtitle': 'سجل دخولك لمتابعة التسوق',
  'phone_number': 'رقم الهاتف',
  'phone_hint': 'أدخل رقم هاتفك',
  'continue_as_guest': 'المتابعة كزائر',
  'send_otp': 'إرسال رمز التحقق',
  'or_continue_with': 'أو المتابعة عبر',
  'continue_with_google': 'المتابعة عبر جوجل',
  'continue_with_apple': 'المتابعة عبر أبل',
  'terms_agreement': 'بالمتابعة، أنت توافق على',
  'terms_of_service': 'شروط الخدمة',
  'privacy_policy': 'سياسة الخصوصية',
  'and': 'و',

  // ── OTP / Verification ─────────────────────────────────
  'verify_phone_title': 'تحقق من الهاتف',
  'verify_phone_subtitle': 'أرسلنا رمز التحقق إلى هاتفك',
  'otp_sent_to': 'تم إرسال الرمز إلى @phone',
  'enter_otp': 'أدخل رمز التحقق',
  'verify_otp': 'تحقق',
  'resend_otp': 'إعادة إرسال الرمز',
  'resend_in': 'إعادة الإرسال خلال @seconds ث',
  'didnt_receive_code': 'لم تستلم الرمز؟',

  // ── Complete Details ────────────────────────────────────
  'complete_details_title': 'أكمل ملفك الشخصي',
  'complete_details_subtitle': 'أخبرنا قليلاً عن نفسك',
  'full_name': 'الاسم الكامل',
  'full_name_hint': 'أدخل اسمك الكامل',
  'email': 'البريد الإلكتروني',
  'email_hint': 'أدخل بريدك الإلكتروني',
  'create_account': 'إنشاء حساب',

  // ── Join Now ────────────────────────────────────────────
  'join_now_title': 'انضم إلى أمازونات',
  'join_now_subtitle': 'اكتشف منتجات مميزة من البائعين المحليين',
  'get_started': 'ابدأ الآن',
  'already_have_account': 'لديك حساب بالفعل؟',
  'login': 'تسجيل الدخول',

  // ── Home Screen ─────────────────────────────────────────
  'home': 'الرئيسية',
  'category': 'الفئات',
  'popular_products': 'المنتجات الشائعة',
  'new_collection': 'مجموعة جديدة',
  'discount_banner': 'خصم 20%\nللأعضاء الجدد',
  'shop_now': 'تسوق الآن',
  'search_products': 'ابحث عن المنتجات',
  'view_all': 'عرض الكل',

  // ── Product ─────────────────────────────────────────────
  'product_details': 'تفاصيل المنتج',
  'details': 'التفاصيل',
  'description': 'الوصف',
  'reviews': 'التقييمات',
  'reviews_and_rating': 'التقييمات والمراجعات',
  'add_to_cart': 'أضف إلى السلة',
  'seller': 'البائع',
  'all_sellers': 'جميع البائعين',
  'learn_more': 'اقرأ المزيد',

  // ── Category ────────────────────────────────────────────
  'categories': 'الفئات',
  'all_categories': 'جميع الفئات',

  // ── Cart ────────────────────────────────────────────────
  'cart': 'السلة',
  'my_cart': 'سلتي',
  'items': '@count عناصر',
  'select_all': 'تحديد الكل',
  'subtotal': 'المجموع الفرعي',
  'discount': 'الخصم',
  'total_cost': 'المجموع الكلي',
  'checkout': 'إتمام الشراء',
  'remove_item': 'إزالة العنصر',
  'empty_cart': 'سلتك فارغة',
  'empty_cart_message': 'يبدو أنك لم تضف أي شيء إلى سلتك بعد',

  // ── Checkout ────────────────────────────────────────────
  'checkout_title': 'إتمام الشراء',
  'delivery_address': 'عنوان التوصيل',
  'payment_method': 'طريقة الدفع',
  'add_card': 'إضافة بطاقة',
  'place_order': 'تأكيد الطلب',
  'order_summary': 'ملخص الطلب',
  'add_new_address': 'إضافة عنوان جديد',
  'complete_payment': 'إتمام الدفع',
  'select_address': 'يرجى اختيار عنوان التوصيل',
  'select_payment': 'يرجى اختيار طريقة الدفع',
  'payment_cancelled': 'تم إلغاء الدفع',
  'payment_cancelled_message': 'لم يتم إكمال عملية الدفع. يمكنك المحاولة مرة أخرى.',
  'order_confirmed': 'تم تأكيد الطلب!',
  'order_confirmed_message': 'تم تقديم طلبك بنجاح',
  'order_on_its_way': 'طلبك في الطريق إليك.',
  'track_my_order': 'تتبع طلبي',
  'continue_shopping': 'متابعة التسوق',
  'show_items': 'عرض المنتجات',
  'hide_items': 'إخفاء المنتجات',
  'generic_error': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',

  // ── Orders ──────────────────────────────────────────────
  'my_orders': 'طلباتي',
  'active': 'نشطة',
  'completed': 'مكتملة',
  'cancelled': 'ملغاة',
  'order_details': 'تفاصيل الطلب',
  'track_order': 'تتبع الطلب',
  'return_order': 'إرجاع',
  'pickup': 'استلام',
  'no_orders': 'لا توجد طلبات بعد',

  // ── Seller ──────────────────────────────────────────────
  'sellers': 'البائعون',
  'follow': 'متابعة',
  'following': 'متابَع',
  'followers': 'المتابعون',
  'closed': 'مغلق',
  'open': 'مفتوح',

  // ── Account / Profile ───────────────────────────────────
  'my_account': 'حسابي',
  'profile': 'الملف الشخصي',
  'address_book':       'دفتر العناوين',
  'pick_address_title': 'اختر عنوان التوصيل',
  'delivery_areas': 'مناطق التوصيل',
  'help_center': 'مركز المساعدة',
  'language': 'اللغة',
  'logout': 'تسجيل الخروج',
  'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',

  // ── Bottom Nav ──────────────────────────────────────────
  'nav_home': 'الرئيسية',
  'nav_category': 'الفئات',
  'nav_seller': 'البائع',
  'nav_cart': 'السلة',
  'nav_account': 'حسابي',

  // ── Products List / Filter ────────────────────────────
  'all_products': 'جميع المنتجات',
  'products_found': '@count منتج',
  'filter_title': 'تصفية',
  'clear_all': 'مسح الكل',
  'apply_filters': 'تطبيق التصفية',
  'sort_by': 'ترتيب حسب',
  'sort_relevance': 'الأكثر صلة',
  'sort_price_low_high': 'السعر: من الأقل',
  'sort_price_high_low': 'السعر: من الأعلى',
  'sort_rating': 'الأعلى تقييماً',
  'price_range': 'نطاق السعر',
  'min_rating': 'الحد الأدنى للتقييم',
  'and_above': 'وأعلى',
  'no_products': 'لا توجد منتجات',
  'no_products_message': 'جرب تعديل الفلاتر أو مصطلح البحث',
  'all_filter': 'الكل',

  // ── Product Details ───────────────────────────────────
  'quantity': 'الكمية',
  'in_stock': 'متوفر',
  'out_of_stock': 'غير متوفر',
  'see_all_reviews': 'عرض جميع التقييمات',
  'view_all_sellers': 'عرض جميع البائعين',
  'share_product': 'مشاركة',
  'added_to_cart': 'تمت الإضافة إلى السلة!',
  'show_less': 'عرض أقل',
  'total_price': 'الإجمالي',

  // ── Address Book ────────────────────────────────────────
  'add_address':              'إضافة عنوان',
  'edit_address':             'تعديل العنوان',
  'address_label':            'اسم العنوان',
  'full_address_field':       'العنوان الكامل',
  'recipient_name':           'اسم المستلم',
  'address_line_1':           'العنوان - السطر الأول',
  'address_line_2':           'العنوان - السطر الثاني',
  'address_line_2_optional':  'الشقة، الطابق، إلخ. (اختياري)',
  'city_field':               'المدينة',
  'state_field':              'المنطقة / الولاية',
  'country_field':            'الدولة',
  'postal_code':              'الرمز البريدي',
  'postal_code_optional':     'الرمز البريدي (اختياري)',
  'set_as_default':           'تعيين كعنوان افتراضي',
  'save_address':             'حفظ العنوان',
  'delete_address':           'حذف العنوان',
  'delete_address_confirm':   'سيتم حذف هذا العنوان نهائيًا.',
  'address_deleted':          'تم حذف العنوان.',
  'default_address_set':      'تم تحديث العنوان الافتراضي',
  'is_now_default':           'هو عنوانك الافتراضي الآن.',
  'no_addresses':             'لا توجد عناوين محفوظة',
  'no_addresses_message':     'أضف عنوانًا لتسريع عملية الدفع.',
  'add_first_address':        'أضف عنوانك الأول',
  'default_badge':            'افتراضي',
  'label_required':           'هذا الحقل مطلوب',
  'address_required':         'يرجى إدخال عنوان صحيح',
  'deleted':                  'تم الحذف',

  // ── Validation ──────────────────────────────────────────
  'required_field': 'هذا الحقل مطلوب',
  'invalid_phone': 'الرجاء إدخال رقم هاتف صحيح',
  'invalid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
  'invalid_otp': 'الرجاء إدخال رمز تحقق صحيح',
  'name_too_short': 'الاسم يجب أن يكون حرفين على الأقل',
};
