const Map<String, String> ar = {
  // ── General ─────────────────────────────────────────────
  'app_name': 'أمازونات',
  'ok': 'حسناً',
  'cancel': 'إلغاء',
  'retry': 'إعادة المحاولة',
  'save': 'حفظ',
  'delete': 'حذف',
  'edit': 'تعديل',
  'search': 'بحث',
  'see_all': 'عرض الكل',
  'continue_text': 'متابعة',
  'loading': 'جاري التحميل...',
  'no_data': 'لا توجد بيانات',
  'error': 'حدث خطأ ما',
  'success': 'تمت العملية بنجاح',

  // ── Auth / Login ────────────────────────────────────────
  'login_title': 'مرحباً بعودتك',
  'login_subtitle': 'سجل دخولك لمتابعة التسوق',
  'phone_number': 'رقم الهاتف',
  'phone_hint': 'أدخل رقم هاتفك',
  'continue_as_guest': 'المتابعة كزائر',
  'send_otp': 'إرسال رمز التحقق',
  'or_continue_with': 'أو المتابعة عبر',
  'continue_with_google': 'المتابعة عبر جوجل',
  'continue_with_apple': 'المتابعة عبر أبل',
  'terms_agreement': 'بالمتابعة، أنت توافق على',
  'terms_of_service': 'شروط الخدمة',
  'privacy_policy': 'سياسة الخصوصية',
  'and': 'و',

  // ── OTP / Verification ─────────────────────────────────
  'verify_phone_title': 'تحقق من الهاتف',
  'verify_phone_subtitle': 'أرسلنا رمز التحقق إلى هاتفك',
  'otp_sent_to': 'تم إرسال الرمز إلى @phone',
  'enter_otp': 'أدخل رمز التحقق',
  'verify_otp': 'تحقق',
  'resend_otp': 'إعادة إرسال الرمز',
  'resend_in': 'إعادة الإرسال خلال @seconds ث',
  'didnt_receive_code': 'لم تستلم الرمز؟',
  'edit_phone': 'تغيير رقم الهاتف',
  'otp_rate_limited': 'تم طلب رموز كثيرة لهذا الرقم. حاول لاحقًا.',
  'otp_too_many_attempts': 'محاولات خاطئة كثيرة. اطلب رمزًا جديدًا.',

  // ── Registration ────────────────────────────────────────
  'no_account_found':   'لا يوجد حساب بهذا الرقم',
  'sign_up_prompt':     'أضف بعض البيانات لإنشاء حسابك.',
  'sign_up':            'إنشاء حساب',
  'first_name_label':   'الاسم الأول',
  'first_name_hint':    'سارة',
  'last_name_label':    'اسم العائلة',
  'last_name_hint':     'محمد',
  'last_name_optional': 'اسم العائلة (اختياري)',

  // ── Complete Details ────────────────────────────────────
  'complete_details_title': 'أكمل ملفك الشخصي',
  'complete_details_subtitle': 'أخبرنا قليلاً عن نفسك',
  'full_name': 'الاسم الكامل',
  'full_name_hint': 'أدخل اسمك الكامل',
  'email': 'البريد الإلكتروني',
  'email_hint': 'أدخل بريدك الإلكتروني',
  'create_account': 'إنشاء حساب',

  // ── Join Now ────────────────────────────────────────────
  'join_now_title': 'انضم إلى أمازونات',
  'join_now_subtitle': 'اكتشف منتجات مميزة من البائعين المحليين',
  'get_started': 'ابدأ الآن',
  'already_have_account': 'لديك حساب بالفعل؟',
  'login': 'تسجيل الدخول',

  // ── Home Screen ─────────────────────────────────────────
  'home': 'الرئيسية',
  'category': 'الفئات',
  'popular_products': 'المنتجات الشائعة',
  'new_collection': 'مجموعة جديدة',
  'discount_banner': 'خصم 20%\nللأعضاء الجدد',
  'shop_now': 'تسوق الآن',
  'search_products': 'ابحث عن المنتجات',
  'view_all': 'عرض الكل',

  // ── Product ─────────────────────────────────────────────
  'product_details': 'تفاصيل المنتج',
  'details': 'التفاصيل',
  'description': 'الوصف',
  'reviews': 'التقييمات',
  'reviews_and_rating': 'التقييمات والمراجعات',
  'add_to_cart': 'أضف إلى السلة',
  'seller': 'البائع',
  'all_sellers': 'جميع البائعين',
  'learn_more': 'اقرأ المزيد',

  // ── Category ────────────────────────────────────────────
  'categories': 'الفئات',
  'all_categories': 'جميع الفئات',

  // ── Cart ────────────────────────────────────────────────
  'cart': 'السلة',
  'my_cart': 'سلتي',
  'items': '@count عناصر',
  'select_all': 'تحديد الكل',
  'subtotal': 'المجموع الفرعي',
  'discount': 'الخصم',
  'total_cost': 'المجموع الكلي',
  'checkout': 'إتمام الشراء',
  'remove_item': 'إزالة العنصر',
  'empty_cart': 'سلتك فارغة',
  'empty_cart_message': 'يبدو أنك لم تضف أي شيء إلى سلتك بعد',

  // ── Checkout ────────────────────────────────────────────
  'checkout_title': 'إتمام الشراء',
  'delivery_address': 'عنوان التوصيل',
  'payment_method': 'طريقة الدفع',
  'add_card': 'إضافة بطاقة',
  'place_order': 'تأكيد الطلب',
  'order_summary': 'ملخص الطلب',
  'add_new_address': 'إضافة عنوان جديد',
  'complete_payment': 'إتمام الدفع',
  'select_address': 'يرجى اختيار عنوان التوصيل',
  'select_payment': 'يرجى اختيار طريقة الدفع',
  'payment_cancelled': 'تم إلغاء الدفع',
  'payment_cancelled_message': 'لم يتم إكمال عملية الدفع. يمكنك المحاولة مرة أخرى.',
  'order_confirmed': 'تم تأكيد الطلب!',
  'order_confirmed_message': 'تم تقديم طلبك بنجاح',
  'order_on_its_way': 'طلبك في الطريق إليك.',
  'track_my_order': 'تتبع طلبي',
  'continue_shopping': 'متابعة التسوق',
  'show_items': 'عرض المنتجات',
  'hide_items': 'إخفاء المنتجات',
  'generic_error': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',

  // ── Orders ──────────────────────────────────────────────
  'my_orders': 'طلباتي',
  'active': 'نشطة',
  'completed': 'مكتملة',
  'cancelled': 'ملغاة',
  'order_details': 'تفاصيل الطلب',
  'track_order': 'تتبع الطلب',
  'return_order': 'إرجاع',
  'pickup': 'استلام',
  'no_orders': 'لا توجد طلبات بعد',
  'no_orders_desc': 'ستظهر طلباتك هنا بمجرد إنشاء طلب.',
  'order_number': 'طلب رقم ',
  'view_details': 'عرض التفاصيل',
  'order_items': 'عناصر الطلب',
  'shipping_fee': 'رسوم الشحن',
  'total_amount': 'الإجمالي',
  'vendor': 'البائع',
  'shipping_address': 'عنوان الشحن',
  'cancel_order': 'إلغاء الطلب',
  'cancel_order_confirm': 'هل تريد إلغاء هذا الطلب؟ لا يمكن التراجع عن ذلك.',
  'cancel_order_reason_hint': 'السبب (اختياري)',
  'order_cancelled': 'تم إلغاء الطلب',
  'order_cancelled_message': 'تم إلغاء طلبك.',
  'order_placed_on': 'تم الطلب في @date',
  'cancellation_reason': 'سبب الإلغاء',
  'status_pending': 'قيد الانتظار',
  'status_paid': 'مدفوع',
  'status_cod': 'الدفع عند الاستلام',
  'status_processing': 'قيد المعالجة',
  'status_shipped': 'تم الشحن',
  'status_ready_for_pickup': 'جاهز للاستلام',
  'status_delivered': 'تم التوصيل',
  'status_cancelled': 'ملغي',
  'status_refunded': 'مسترد',
  'status_unknown': 'غير معروف',

  // ── Seller ──────────────────────────────────────────────
  'sellers': 'البائعون',
  'view_store': 'زيارة المتجر',
  'store_products': 'المنتجات',
  'no_store_products': 'لا توجد منتجات لدى هذا البائع بعد',
  'search_sellers': 'ابحث عن بائع',
  'no_sellers': 'لا يوجد بائعون',
  'no_sellers_message': 'جرّب بحثًا مختلفًا أو عد لاحقًا.',
  'verified': 'موثّق',
  'follow': 'متابعة',
  'following': 'متابَع',
  'followers': 'المتابعون',
  'closed': 'مغلق',
  'open': 'مفتوح',

  // ── Account / Profile ───────────────────────────────────
  'my_account': 'حسابي',
  'profile': 'الملف الشخصي',
  'address_book':       'دفتر العناوين',
  'pick_address_title': 'اختر عنوان التوصيل',
  'delivery_areas': 'مناطق التوصيل',
  'help_center': 'مركز المساعدة',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'الإنجليزية',
  'logout': 'تسجيل الخروج',
  'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',

  // ── Bottom Nav ──────────────────────────────────────────
  'request_refund': 'طلب استرداد',
  'refund_type': 'نوع الاسترداد',
  'refund_type_full': 'كامل',
  'refund_type_partial': 'جزئي',
  'refund_reason': 'السبب',
  'refund_reason_hint': 'اختر سببًا',
  'refund_explanation': 'أخبرنا بما حدث',
  'select_items': 'العناصر المراد استردادها',
  'select_at_least_one_item': 'اختر عنصرًا واحدًا على الأقل',
  'payout_method': 'طريقة الاستلام',
  'submit_refund': 'إرسال الطلب',
  'refund_requested': 'تم إرسال الطلب',
  'refund_requested_message': 'سنراجع طلبك ونرتب موعد الاستلام.',
  'field_required': 'هذا الحقل مطلوب',
  'field_invalid': 'يرجى مراجعة هذه القيمة',
  'refund_tracker': 'المستردات',
  'refund_amount': 'المبلغ',
  'refund_requested_at': 'تاريخ الطلب',
  'refund_completed_at': 'تاريخ الإتمام',
  'transport_cost': 'تكلفة النقل',
  'decline_reason': 'سبب الرفض',
  'payouts': 'المدفوعات',
  'pickup_schedule': 'الاستلام',
  'refund_status_pending': 'قيد الانتظار',
  'refund_status_under_processing': 'قيد المعالجة',
  'refund_status_under_review': 'قيد المراجعة',
  'refund_status_awaiting_payout': 'بانتظار الدفع',
  'refund_status_rejected': 'مرفوض',
  'refund_status_refunded': 'تم الاسترداد',
  'payout_status_pending': 'قيد الانتظار',
  'payout_status_processing': 'قيد المعالجة',
  'payout_status_approved': 'تمت الموافقة',
  'payout_status_completed': 'مكتمل',
  'payout_status_declined': 'مرفوض',
  'edfali_wallet': 'رقم محفظة إدفعلي',
  'edfali_wallet_hint': '09XXXXXXXX',
  'edfali_confirm_title': 'تأكيد الدفع',
  'edfali_code_sent_to': 'أدخل الرمز المُرسل إلى @phone',
  'edfali_attempts_remaining': 'تبقّى @count محاولات',
  'edfali_otp_invalid': 'رمز غير صحيح. حاول مرة أخرى.',
  'edfali_attempts_exceeded': 'محاولات خاطئة كثيرة. تم إلغاء الطلب.',
  'edfali_session_expired': 'انتهت جلسة الدفع. يرجى إعادة الطلب.',
  'edfali_payment_failed': 'فشلت عملية الدفع. جرّب طريقة أخرى.',
  'payment_under_review': 'الدفع قيد المراجعة',
  'payment_under_review_message': 'نتحقق من هذه العملية مع المزود. لا حاجة لأي إجراء.',
  'confirm_payment': 'تأكيد الدفع',
  'single_seller_checkout': 'اختر عناصر من بائع واحد في كل عملية شراء.',
  'nav_home': 'الرئيسية',
  'nav_category': 'الفئات',
  'nav_seller': 'البائع',
  'nav_cart': 'السلة',
  'nav_account': 'حسابي',

  // ── Products List / Filter ────────────────────────────
  'all_products': 'جميع المنتجات',
  'products_found': '@count منتج',
  'filter_title': 'تصفية',
  'clear_all': 'مسح الكل',
  'apply_filters': 'تطبيق التصفية',
  'sort_by': 'ترتيب حسب',
  'sort_relevance': 'الأكثر صلة',
  'sort_price_low_high': 'السعر: من الأقل',
  'sort_price_high_low': 'السعر: من الأعلى',
  'sort_rating': 'الأعلى تقييماً',
  'sort_name_asc': 'الاسم: أ إلى ي',
  'search_results_for': 'نتائج البحث عن',
  'active_filters': 'الفلاتر النشطة',
  'search_hint': 'ابحث عن المنتجات...',
  'price_range': 'نطاق السعر',
  'min_rating': 'الحد الأدنى للتقييم',
  'and_above': 'وأعلى',
  'no_products': 'لا توجد منتجات',
  'no_products_message': 'جرب تعديل الفلاتر أو مصطلح البحث',
  'all_filter': 'الكل',

  // ── Product Details ───────────────────────────────────
  'quantity': 'الكمية',
  'in_stock': 'متوفر',
  'out_of_stock': 'غير متوفر',
  'see_all_reviews': 'عرض جميع التقييمات',
  'view_all_sellers': 'عرض جميع البائعين',
  'share_product': 'مشاركة',
  'added_to_cart': 'تمت الإضافة إلى السلة!',
  'show_less': 'عرض أقل',
  'total_price': 'الإجمالي',

  // ── Address Book ────────────────────────────────────────
  'add_address':              'إضافة عنوان',
  'edit_address':             'تعديل العنوان',
  'address_label':            'اسم العنوان',
  'full_address_field':       'العنوان الكامل',
  'recipient_name':           'اسم المستلم',
  'address_line_1':           'العنوان - السطر الأول',
  'address_line_2':           'العنوان - السطر الثاني',
  'address_line_2_optional':  'الشقة، الطابق، إلخ. (اختياري)',
  'city_field':               'المدينة',
  'state_field':              'المنطقة / الولاية',
  'country_field':            'الدولة',
  'postal_code':              'الرمز البريدي',
  'postal_code_optional':     'الرمز البريدي (اختياري)',
  'set_as_default':           'تعيين كعنوان افتراضي',
  'save_address':             'حفظ العنوان',
  'delete_address':           'حذف العنوان',
  'delete_address_confirm':   'سيتم حذف هذا العنوان نهائيًا.',
  'address_deleted':          'تم حذف العنوان.',
  'default_address_set':      'تم تحديث العنوان الافتراضي',
  'is_now_default':           'هو عنوانك الافتراضي الآن.',
  'no_addresses':             'لا توجد عناوين محفوظة',
  'no_addresses_message':     'أضف عنوانًا لتسريع عملية الدفع.',
  'add_first_address':        'أضف عنوانك الأول',
  'default_badge':            'افتراضي',
  'label_required':           'هذا الحقل مطلوب',
  'address_required':         'يرجى إدخال عنوان صحيح',
  'deleted':                  'تم الحذف',

  // ── Notifications ───────────────────────────────────────
  'notifications':                 'الإشعارات',
  'notifications_description':     'عرض وإدارة الإشعارات الخاصة بك.',
  'notifications_all':             'الكل',
  'notifications_unread':          'غير المقروءة',
  'notifications_read':            'المقروءة',
  'mark_read':                     'تحديد كمقروء',
  'mark_all_read':                 'تحديد الكل كمقروء',
  'no_notifications':              'لا توجد إشعارات',
  'no_notifications_message':      'لقد اطلعت على كل شيء. ستظهر الإشعارات الجديدة هنا.',
  'all_notifications_marked_read': 'تم تحديد جميع الإشعارات كمقروءة',

  // ── Relative Time ───────────────────────────────────────
  'time_just_now':    'الآن',
  'time_minutes_ago': 'منذ @count دقيقة',
  'time_hours_ago':   'منذ @count ساعة',
  'time_days_ago':    'منذ @count يوم',
  'time_weeks_ago':   'منذ @count أسبوع',
  'time_months_ago':  'منذ @count شهر',
  'time_years_ago':   'منذ @count سنة',

  // ── Validation ──────────────────────────────────────────
  'required_field': 'هذا الحقل مطلوب',
  'invalid_phone': 'الرجاء إدخال رقم هاتف صحيح',
  'invalid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
  'invalid_otp': 'الرجاء إدخال رمز تحقق صحيح',
  'name_too_short': 'الاسم يجب أن يكون حرفين على الأقل',
};
