const Map<String, String> ar = {
  // ── General ─────────────────────────────────────────────
  'app_name': 'أمازونات',
  'ok': 'حسناً',
  'cancel': 'إلغاء',
  'retry': 'إعادة المحاولة',
  'save': 'حفظ',
  'delete': 'حذف',
  'search': 'بحث',
  'see_all': 'عرض الكل',
  'continue_text': 'متابعة',
  'loading': 'جاري التحميل...',
  'no_data': 'لا توجد بيانات',
  'error': 'حدث خطأ ما',
  'success': 'تمت العملية بنجاح',

  // ── Auth / Login ────────────────────────────────────────
  'login_title': 'مرحباً بعودتك',
  'login_subtitle': 'سجل دخولك لمتابعة التسوق',
  'phone_number': 'رقم الهاتف',
  'phone_hint': 'أدخل رقم هاتفك',
  'continue_as_guest': 'المتابعة كزائر',
  'send_otp': 'إرسال رمز التحقق',
  'or_continue_with': 'أو المتابعة عبر',
  'continue_with_google': 'المتابعة عبر جوجل',
  'continue_with_apple': 'المتابعة عبر أبل',
  'terms_agreement': 'بالمتابعة، أنت توافق على',
  'terms_of_service': 'شروط الخدمة',
  'privacy_policy': 'سياسة الخصوصية',
  'and': 'و',

  // ── OTP / Verification ─────────────────────────────────
  'verify_phone_title': 'تحقق من الهاتف',
  'verify_phone_subtitle': 'أرسلنا رمز التحقق إلى هاتفك',
  'otp_sent_to': 'تم إرسال الرمز إلى @phone',
  'enter_otp': 'أدخل رمز التحقق',
  'verify_otp': 'تحقق',
  'resend_otp': 'إعادة إرسال الرمز',
  'resend_in': 'إعادة الإرسال خلال @seconds ث',
  'didnt_receive_code': 'لم تستلم الرمز؟',
  'edit_phone': 'تغيير رقم الهاتف',
  'otp_rate_limited': 'تم طلب رموز كثيرة لهذا الرقم. حاول لاحقًا.',
  'otp_too_many_attempts': 'محاولات خاطئة كثيرة. اطلب رمزًا جديدًا.',

  // ── Registration ────────────────────────────────────────
  'no_account_found':   'لا يوجد حساب بهذا الرقم',
  'sign_up_prompt':     'أضف بعض البيانات لإنشاء حسابك.',
  'sign_up':            'إنشاء حساب',
  'first_name_label':   'الاسم الأول',
  'first_name_hint':    'سارة',
  'last_name_label':    'اسم العائلة',
  'last_name_hint':     'محمد',
  'last_name_optional': 'اسم العائلة (اختياري)',

  // ── Complete Details ────────────────────────────────────
  'complete_details_title': 'أكمل ملفك الشخصي',
  'complete_details_subtitle': 'أخبرنا قليلاً عن نفسك',
  'full_name': 'الاسم الكامل',
  'full_name_hint': 'أدخل اسمك الكامل',
  'email': 'البريد الإلكتروني',
  'email_hint': 'أدخل بريدك الإلكتروني',
  'create_account': 'إنشاء حساب',

  // ── Join Now ────────────────────────────────────────────
  'join_now_title': 'انضم إلى أمازونات',
  'join_now_subtitle': 'اكتشف منتجات مميزة من البائعين المحليين',
  'get_started': 'ابدأ الآن',
  'already_have_account': 'لديك حساب بالفعل؟',
  'login': 'تسجيل الدخول',

  // ── Home Screen ─────────────────────────────────────────
  'home': 'الرئيسية',
  'category': 'الفئات',
  'popular_products': 'المنتجات الشائعة',
  'new_collection': 'مجموعة جديدة',
  'discount_banner': 'خصم 20%\nللأعضاء الجدد',
  'shop_now': 'تسوق الآن',
  'know_more': 'اعرف المزيد',
  'search_products': 'ابحث عن المنتجات',
  'view_all': 'عرض الكل',

  // ── Product ─────────────────────────────────────────────
  'product_details': 'تفاصيل المنتج',
  'details': 'التفاصيل',
  'description': 'الوصف',
  'reviews': 'التقييمات',
  'reviews_and_rating': 'التقييمات والمراجعات',
  'add_to_cart': 'أضف إلى السلة',
  'seller': 'البائع',
  'all_sellers': 'جميع البائعين',
  'learn_more': 'اقرأ المزيد',

  // ── Category ────────────────────────────────────────────
  'categories': 'الفئات',
  'all_categories': 'جميع الفئات',

  // ── Cart ────────────────────────────────────────────────
  'cart': 'السلة',
  'my_cart': 'سلتي',
  'items': '@count عناصر',
  'select_all': 'تحديد الكل',
  'subtotal': 'المجموع الفرعي',
  'discount': 'الخصم',
  'total_cost': 'المجموع الكلي',
  'checkout': 'إتمام الشراء',
  'remove_item': 'إزالة العنصر',
  'empty_cart': 'سلتك فارغة',
  'empty_cart_message': 'يبدو أنك لم تضف أي شيء إلى سلتك بعد',

  // ── Checkout ────────────────────────────────────────────
  'checkout_title': 'إتمام الشراء',
  'delivery_address': 'عنوان التوصيل',
  'payment_method': 'طريقة الدفع',
  'add_card': 'إضافة بطاقة',
  'place_order': 'تأكيد الطلب',
  'order_summary': 'ملخص الطلب',
  'add_new_address': 'إضافة عنوان جديد',
  'complete_payment': 'إتمام الدفع',
  'select_address': 'يرجى اختيار عنوان التوصيل',
  'select_payment': 'يرجى اختيار طريقة الدفع',
  'payment_cancelled': 'لم يكتمل الدفع',
  'payment_cancelled_message': 'أُلغيت عملية الدفع ولم يُخصم أي مبلغ. طلبك ما زال محفوظاً في السلة.',
  'order_confirmed': 'تم استلام طلبك',
  'order_confirmed_message': 'شكراً لك. المتجر يجهّز طلبك الآن، وتصلك إشعارات بكل تغيّر في حالته.',
  'order_on_its_way': 'طلبك في الطريق إليك.',
  'track_my_order': 'تتبع طلبي',
  'continue_shopping': 'متابعة التسوق',
  'show_items': 'عرض المنتجات',
  'hide_items': 'إخفاء المنتجات',
  'generic_error': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',

  // ── Orders ──────────────────────────────────────────────
  'my_orders': 'طلباتي',
  'active': 'نشطة',
  'completed': 'مكتملة',
  'cancelled': 'ملغاة',
  'order_details': 'تفاصيل الطلب',
  'track_order': 'تتبع الطلب',
  'return_order': 'إرجاع',
  'pickup': 'استلام',
  'no_orders': 'لا توجد طلبات بعد',
  'no_orders_desc': 'ستظهر طلباتك هنا بمجرد إنشاء طلب.',
  'order_number': 'طلب رقم ',
  'view_details': 'عرض التفاصيل',
  'order_items': 'عناصر الطلب',
  'shipping_fee': 'رسوم الشحن',
  'total_amount': 'الإجمالي',
  'vendor': 'البائع',
  'shipping_address': 'عنوان الشحن',
  'cancel_order': 'إلغاء الطلب',
  'cancel_order_confirm': 'هل تريد إلغاء هذا الطلب؟ لا يمكن التراجع عن ذلك.',
  'cancel_order_reason_hint': 'السبب (اختياري)',
  'order_cancelled': 'تم إلغاء الطلب',
  'order_cancelled_message': 'تم إلغاء طلبك.',
  'order_placed_on': 'تم الطلب في @date',
  'cancellation_reason': 'سبب الإلغاء',
  'status_pending': 'قيد الانتظار',
  'status_paid': 'مدفوع',
  'status_cod': 'الدفع عند الاستلام',
  'status_processing': 'قيد المعالجة',
  'status_shipped': 'تم الشحن',
  'status_ready_for_pickup': 'جاهز للاستلام',
  'status_delivered': 'تم التوصيل',
  'status_cancelled': 'ملغي',
  'status_refunded': 'مسترد',
  'status_unknown': 'غير معروف',

  // ── Seller ──────────────────────────────────────────────
  'sellers': 'البائعون',
  'view_store': 'زيارة المتجر',
  'store_products': 'المنتجات',
  'no_store_products': 'لا توجد منتجات لدى هذا البائع بعد',
  'search_sellers': 'ابحث عن بائع',
  'no_sellers': 'لا يوجد بائعون',
  'no_sellers_message': 'جرّب بحثًا مختلفًا أو عد لاحقًا.',
  'verified': 'موثّق',
  'follow': 'متابعة',
  'following': 'متابَع',
  'followers': 'المتابعون',
  'closed': 'مغلق',
  'open': 'مفتوح',

  // ── Account / Profile ───────────────────────────────────
  'my_account': 'حسابي',
  'profile': 'الملف الشخصي',
  'address_book':       'دفتر العناوين',
  'pick_address_title': 'اختر عنوان التوصيل',
  'delivery_areas': 'مناطق التوصيل',
  'help_center': 'مركز المساعدة',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'الإنجليزية',
  'logout': 'تسجيل الخروج',
  'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',

  // ── Bottom Nav ──────────────────────────────────────────
  'request_refund': 'طلب استرداد',
  'refund_type': 'نوع الاسترداد',
  'refund_type_full': 'الطلب كامل',
  'refund_type_partial': 'بعض المنتجات',
  'refund_reason': 'السبب',
  'refund_reason_hint': 'اختر سببًا',
  'refund_explanation': 'أخبرنا بما حدث',
  'select_items': 'العناصر المراد استردادها',
  'select_at_least_one_item': 'اختر عنصرًا واحدًا على الأقل',
  'payout_method': 'طريقة الاستلام',
  'submit_refund': 'إرسال الطلب',
  'refund_requested': 'تم إرسال الطلب',
  'refund_requested_message': 'سنراجع طلبك ونرتب موعد الاستلام.',
  'field_required': 'هذا الحقل مطلوب',
  'field_invalid': 'يرجى مراجعة هذه القيمة',
  'refund_tracker': 'المستردات',
  'back': 'رجوع',
  'refund_label': 'استرجاع',
  'refund_tracking': 'متابعة الاسترداد',
  'refund_track': 'تتبّع',
  'refund_next': 'الخطوة التالية',
  'refund_next_pending': 'وصل طلبك إلى المتجر وسيُراجَع قريباً.',
  'refund_next_under_review': 'يراجع المتجر طلبك والمنتجات المرتجعة.',
  'refund_next_under_processing': 'سنستلم المنتجات في الموعد المحدَّد، ثم يُصرف المبلغ.',
  'refund_next_awaiting_payout': 'المبلغ في طريقه إلى طريقة الاستلام التي اخترتها.',
  'refund_net_amount': 'صافي المبلغ المحوَّل',
  'refund_eligible_lead': 'هل هناك مشكلة؟',
  'refund_eligible_title': 'يمكنك طلب استرداد لهذا الطلب',
  'refund_eligible_collect': 'نأتي لاستلام المنتجات. تحدّد معنا موعداً وعنواناً للاستلام.',
  'refund_eligible_money': 'ثم يُحوَّل المبلغ. إلى الطريقة التي تختارها، بعد خصم تكلفة النقل.',
  'refund_amount': 'المبلغ',
  'refund_requested_at': 'تاريخ طلب الاسترداد',
  'refund_requested_short': 'طُلب',
  'refund_completed_at': 'تاريخ الإتمام',
  'transport_cost': 'تكلفة النقل',
  'decline_reason': 'سبب الرفض',
  'payouts': 'المدفوعات',
  'pickup_schedule': 'الاستلام',
  'refund_status_pending': 'قيد الانتظار',
  'refund_status_under_processing': 'قيد المعالجة',
  'refund_status_under_review': 'قيد المراجعة',
  'refund_status_awaiting_payout': 'بانتظار الدفع',
  'refund_status_rejected': 'مرفوض',
  'refund_status_refunded': 'تم الاسترداد',
  'payout_status_pending': 'قيد الانتظار',
  'payout_status_processing': 'قيد المعالجة',
  'payout_status_approved': 'تمت الموافقة',
  'payout_status_completed': 'مكتمل',
  'payout_status_declined': 'مرفوض',
  'transaction_proof': 'إثبات التحويل',
  'transaction_proof_hint': 'اضغط للعرض',
  'save_to_photos': 'حفظ في الصور',
  'proof_saved': 'تم حفظ الإثبات في صورك',
  'proof_save_failed': 'تعذّر حفظ الإثبات. حاول مرة أخرى.',
  'photos_permission_denied': 'اسمح بالوصول إلى الصور لحفظ الإثبات.',
  'edfali_wallet': 'رقم محفظة إدفعلي',
  'edfali_wallet_hint': '09XXXXXXXX',
  'edfali_confirm_title': 'تأكيد الدفع',
  'edfali_code_sent_to': 'أدخل الرمز المُرسل إلى @phone',
  'edfali_attempts_remaining': 'تبقّى @count محاولات',
  'edfali_otp_invalid': 'رمز غير صحيح. حاول مرة أخرى.',
  'edfali_attempts_exceeded': 'محاولات خاطئة كثيرة. تم إلغاء الطلب.',
  'edfali_session_expired': 'انتهت جلسة الدفع. يرجى إعادة الطلب.',
  'edfali_payment_failed': 'فشلت عملية الدفع. جرّب طريقة أخرى.',
  'payment_under_review': 'الدفع قيد المراجعة',
  'payment_under_review_message': 'نتحقق من هذه العملية مع المزود. لا حاجة لأي إجراء.',
  'confirm_payment': 'تأكيد الدفع',
  'single_seller_checkout': 'اختر عناصر من بائع واحد في كل عملية شراء.',
  'nav_home': 'الرئيسية',
  'nav_category': 'الفئات',
  'nav_seller': 'البائع',
  'nav_cart': 'السلة',
  'nav_account': 'حسابي',

  // ── Products List / Filter ────────────────────────────
  'all_products': 'جميع المنتجات',
  'products_found': '@count منتج',
  'filter_title': 'تصفية',
  'clear_all': 'مسح الكل',
  'apply_filters': 'تطبيق التصفية',
  'sort_by': 'ترتيب حسب',
  'sort_relevance': 'الأكثر صلة',
  'sort_price_low_high': 'السعر: من الأقل',
  'sort_price_high_low': 'السعر: من الأعلى',
  'sort_rating': 'الأعلى تقييماً',
  'sort_name_asc': 'الاسم: أ إلى ي',
  'search_results_for': 'نتائج البحث عن',
  'active_filters': 'الفلاتر النشطة',
  'search_hint': 'ابحث عن المنتجات...',
  'price_range': 'نطاق السعر',
  'min_rating': 'الحد الأدنى للتقييم',
  'and_above': 'وأعلى',
  'no_products': 'لا توجد منتجات',
  'no_products_message': 'جرب تعديل الفلاتر أو مصطلح البحث',
  'all_filter': 'الكل',

  // ── Product Details ───────────────────────────────────
  'quantity': 'الكمية',
  'in_stock': 'متوفر',
  'out_of_stock': 'غير متوفر',
  'see_all_reviews': 'عرض جميع التقييمات',
  'view_all_sellers': 'عرض جميع البائعين',
  'share_product': 'مشاركة',
  'added_to_cart': 'تمت الإضافة إلى السلة!',
  'show_less': 'عرض أقل',
  'total_price': 'الإجمالي',

  // ── Address Book ────────────────────────────────────────
  'add_address':              'إضافة عنوان',
  'address_label':            'اسم العنوان',
  'full_address_field':       'العنوان الكامل',
  'recipient_name':           'اسم المستلم',
  'address_line_1':           'العنوان - السطر الأول',
  'address_line_2':           'العنوان - السطر الثاني',
  'address_line_2_optional':  'الشقة، الطابق، إلخ. (اختياري)',
  'city_field':               'المدينة',
  'state_field':              'المنطقة / الولاية',
  'country_field':            'الدولة',
  'postal_code':              'الرمز البريدي',
  'postal_code_optional':     'الرمز البريدي (اختياري)',
  'set_as_default':           'تعيين كعنوان افتراضي',
  'save_address':             'حفظ العنوان',
  'delete_address':           'حذف العنوان',
  'delete_address_confirm':   'سيتم حذف هذا العنوان نهائيًا.',
  'address_deleted':          'تم حذف العنوان.',
  'default_address_set':      'تم تحديث العنوان الافتراضي',
  'is_now_default':           'هو عنوانك الافتراضي الآن.',
  'no_addresses':             'لا توجد عناوين محفوظة',
  'no_addresses_message':     'أضف عنوانًا لتسريع عملية الدفع.',
  'add_first_address':        'أضف عنوانك الأول',
  'default_badge':            'افتراضي',
  'label_required':           'هذا الحقل مطلوب',
  'address_required':         'يرجى إدخال عنوان صحيح',
  'deleted':                  'تم الحذف',

  // ── Notifications ───────────────────────────────────────
  'notifications':                 'الإشعارات',
  'notifications_description':     'عرض وإدارة الإشعارات الخاصة بك.',
  'notifications_all':             'الكل',
  'notifications_unread':          'غير المقروءة',
  'notifications_read':            'المقروءة',
  'mark_read':                     'تحديد كمقروء',
  'mark_all_read':                 'تحديد الكل كمقروء',
  'no_notifications':              'لا توجد إشعارات',
  'no_notifications_message':      'لقد اطلعت على كل شيء. ستظهر الإشعارات الجديدة هنا.',
  'all_notifications_marked_read': 'تم تحديد جميع الإشعارات كمقروءة',

  // ── Relative Time ───────────────────────────────────────
  'time_just_now':    'الآن',
  'time_minutes_ago': 'منذ @count دقيقة',
  'time_hours_ago':   'منذ @count ساعة',
  'time_days_ago':    'منذ @count يوم',
  'time_weeks_ago':   'منذ @count أسبوع',
  'time_months_ago':  'منذ @count شهر',
  'time_years_ago':   'منذ @count سنة',

  // ── Validation ──────────────────────────────────────────
  'required_field': 'هذا الحقل مطلوب',
  'invalid_phone': 'الرجاء إدخال رقم هاتف صحيح',
  'invalid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
  'invalid_otp': 'الرجاء إدخال رمز تحقق صحيح',
  'name_too_short': 'الاسم يجب أن يكون حرفين على الأقل',
  'new_arrivals': 'وصل حديثاً',
  'featured_stores': 'متاجر مميزة',
  'all_categories_filter': 'الكل',
  'search_home_hint': 'ابحث عن منتجات أو متاجر…',
  'appearance': 'المظهر',
  'theme_light': 'فاتح',
  'theme_dark': 'داكن',
  'theme_system': 'حسب النظام',
  'home_hero_title': 'صناعة ليبية يدوية',
  'order_progress': 'مراحل الطلب',
  'step_placed': 'تم الطلب',
  'step_paid': 'تم الدفع',
  'step_shipped': 'تم الشحن',
  'step_delivered': 'تم التسليم',
  'total_paid': 'الإجمالي المدفوع',
  'sold_shipped_by': 'يُباع ويُشحن من هذا المتجر',
  'orders_count': '@count طلب',
  'orders_on_the_way': '@count قيد التوصيل',
  'items_count': '@count منتج',
  'items_count_one': 'منتج واحد',
  'sellers_subtitle': 'حرفيون ليبيون يبيعون مباشرة من ورشهم',
  'chat_on_whatsapp': 'تواصل عبر واتساب',
  'clear_search': 'مسح البحث',
  'loading_more_sellers': 'جارٍ تحميل المزيد من المتاجر…',
  'products_label': 'المنتجات',
  'group_today': 'اليوم',
  'group_yesterday': 'أمس',
  'group_earlier': 'في وقت سابق',
  'unread_of_total': 'لديك @unread إشعارات غير مقروءة من أصل @total',
  'view_order_action': 'عرض الطلب',
  'cart_total': 'إجمالي السلة',
  'cart_stores_note': 'كل متجر يُدفع على حدة، ورسوم الشحن تُحسب داخل صفحة الدفع لكل متجر.',
  'cart_items_from': '@items من @stores',
  'you_saved': 'وفّرت',
  'paying_store': 'الدفع لمتجر',
  'stores_count': '@count متاجر',
  'stores_count_one': 'متجر واحد',
  'best_sellers': 'الأكثر مبيعاً',
  'admin_picks': 'اختيارات المحرر',
  'read_more': 'اقرأ المزيد',
  'read_less': 'عرض أقل',
  'weight_label': 'الوزن',
  'sku_label': 'رمز المنتج',
  'added_label': 'أُضيف في',
  'more_from_store': 'من نفس المتجر',
  'available_now_store': 'متوفر الآن من نفس المتجر',
  'not_available_order': 'غير متاح للطلب',
  'currently_unavailable': 'غير متاح حاليًا',
  'out_of_stock_note': 'هذا المنتج غير متاح للطلب حاليًا. تصفّح باقي منتجات المتجر أو عُد لاحقًا.',
  'product_not_found': 'المنتج غير موجود',
  'product_not_found_body': 'قد لا يكون هذا المنتج متاحًا بعد الآن، أو أن البائع قام بإزالته من المتجر.',
  'browse_products': 'تصفّح المنتجات',
  'loading_product': 'جارٍ تحميل المنتج…',
  'pay_edfali_hint': 'يصلك رمز تحقق برسالة نصية',
  'pay_cod_hint': 'تدفع نقداً عند وصول الطلب',
  'pay_gateway_hint': 'سيتم تحويلك إلى صفحة الدفع',
  'shipping_pending': 'تُحسب بعد اختيار العنوان',
  'amount_paid': 'المبلغ المدفوع',
  'amount_label': 'المبلغ',
  'status_label': 'الحالة',
  'back_to_cart': 'العودة إلى السلة',
  'edfali_lead': 'أرسلت إدفعلي رمز تحقق إلى @phone. أدخل الرمز لإتمام الدفع.',
  'code_expires_in': 'ينتهي الرمز خلال',
  'edfali_hold_warn': 'لا تغلق هذه الشاشة قبل التأكيد — طلبك محجوز مؤقتاً ويُلغى تلقائياً إذا انتهت مهلة الرمز.',
  'edfali_no_resend': 'بعد التأكيد يبدأ المتجر بتجهيز طلبك، وتصلك إشعارات بكل تغيّر في حالته. لا توجد خدمة لإعادة إرسال الرمز — إذا انتهت المهلة أعد الطلب من السلة.',
  'price_from': 'من',
  'price_to': 'إلى',
  'search_the_market': 'ابحث في السوق',
  'search_subtitle': 'منتجات يدوية من متاجر ليبية',
  'recent_searches': 'عمليات البحث الأخيرة',
  'shop_by': 'تسوّق حسب',
  'browse_categories': 'تصفّح الفئات',
  'subcategories_count': '@count أقسام فرعية',
  'no_subcategories': 'لا توجد أقسام فرعية',
  'pull_to_refresh': 'اسحب للتحديث',
  'clear_filters': 'مسح التصفية',
  'loading_more': 'جارٍ تحميل المزيد…',
  'categories_title': 'الفئات',
  'categories_subtitle': 'كل الحرف في السوق',
  'all_products_title': 'كل المنتجات',
  'search_hint_short': 'ابحث عن المنتجات…',
  'splash_tagline': 'سوق ليبيا للمشغولات اليدوية — من يد الصانع إلى بابك',
  'made_in_libya': 'صُنع في ليبيا',
  'onboard_1_title': 'مباشرة من الورشة',
  'onboard_1_body': 'كل قطعة يبيعها الحرفي الليبي الذي صنعها — لا وسيط بين طاولته وبابك.',
  'onboard_2_title': 'ادفع كما يناسبك',
  'onboard_2_body': 'أكّد الدفع برمز إدفعلي، أو ادفع نقداً عند وصول الطلب.',
  'onboard_3_title': 'تابع طلبك حتى الباب',
  'onboard_3_body': 'تتبّع كل طلب من الورشة إلى مدينتك، ويصلك إشعار عند كل مرحلة.',
  'skip': 'تخطّي',
  'next': 'التالي',
  'start_shopping': 'ابدأ التسوّق',
  'welcome_title': 'أهلاً بك في أمازونات',
  'welcome_subtitle': 'سجّل الدخول برقم هاتفك لتبدأ التسوّق.',
  'trust_payment': 'إدفعلي أو الدفع عند الاستلام',
  'trust_stores': 'متاجر ليبية موثّقة',
  'trust_delivery': 'توصيل إلى كل المدن',
  'sms_language': 'لغة رسالة الرمز',
  'first_time_note': 'أول مرة هنا؟ سنطلب اسمك وبريدك الإلكتروني قبل إرسال الرمز.',
  'step_enter_phone': 'أدخل رقم هاتفك',
  'step_enter_code': 'أدخل الرمز الذي نرسله لك',
  'optional_chip': 'اختياري',
  'create_account_subtitle': 'نحتاج هذه البيانات قبل أن نرسل لك الرمز.',
  'code_sent_to_phone': 'أرسلنا رمزاً إلى @phone',
  'map_location': 'الموقع على الخريطة',
  'map_pin_hint': 'حرّك الخريطة حتى يستقر المؤشّر على بابك، ثم أكّد.',
  'confirm_location': 'تأكيد هذا الموقع',
  'change_location': 'تغيير',
  'location_required': 'يرجى تحديد موقعك على الخريطة',
  'location_pinned': 'تم تحديد الموقع',
  'map_moving': 'جارٍ تحريك الخريطة…',
  'map_moving_hint': 'ارفع إصبعك ليُقرأ العنوان عند المؤشّر',
  'resolving_address': 'جارٍ تحديد العنوان…',
  'no_street_address': 'لا يوجد عنوان شارع هنا',
  'no_street_address_hint':
      'سنحفظ الإحداثيات بالضبط — يصل المندوب إلى المؤشّر.',
  'coordinates': 'الإحداثيات المحفوظة',
  'coordinates_live': 'تتغيّر مع حركة الخريطة',
  'location_services_off':
      'خدمة الموقع مُعطّلة، لذا لا يمكننا الانتقال إلى مكانك. حدّد بابك يدويًا، أو',
  'location_permission_denied':
      'إذن الموقع مرفوض، لذا لا يمكننا الانتقال إلى مكانك. حدّد بابك يدويًا، أو',
  'open_settings': 'افتح الإعدادات',
  'my_location': 'موقعي',
  'invalid_libyan_phone': 'أدخل رقم هاتف ليبي صحيح (9 أرقام)',
  'select_city': 'اختيار المدينة',
  'search_city': 'ابحث عن مدينة',
  'district_optional': 'المنطقة (اختياري)',
  'fix_fields': 'يرجى تصحيح @count حقول',
  'section_shopping': 'التسوّق',
  'section_preferences': 'التفضيلات',
  'section_account': 'الحساب',
  'stat_orders': 'الطلبات',
  'stat_addresses': 'العناوين',
  'stat_unread': 'غير مقروء',
  'default_address': 'العنوان الافتراضي',
  'my_addresses': 'عناويني',
  'addresses_subtitle': 'أين تُسلَّم طلباتك',
  'refund_type_full_hint': 'إرجاع كل ما في هذا الطلب',
  'refund_type_partial_hint': 'اختر ما ترغب بإرجاعه',
  'refund_which_items': 'المنتجات',
  'refund_reason_pick': 'السبب',
  'refund_reason_pick_hint': 'اختر سبباً',
  'refund_tell_us': 'أخبرنا بما حدث',
  'refund_tell_us_hint': 'صف المشكلة في جملة أو جملتين',
  'refund_payout_method': 'أين نرسل المبلغ',
  'refund_review': 'المراجعة',
  'refund_estimate': 'مبلغ الاسترداد التقديري',
  'refund_estimate_note': 'مبلغ تقديري. يخصم المتجر تكلفة النقل بعد المراجعة، لذا قد يقل المبلغ الذي يصلك.',
  'refund_step_1': 'المنتجات والسبب',
  'refund_step_2': 'طريقة الاستلام',
  'refund_continue': 'متابعة',
  'refund_submit': 'إرسال الطلب',
  'refund_no_payout_methods': 'لا توجد طرق استلام متاحة حالياً. حاول لاحقاً.',
  'refund_items_count': '@count من @total منتجات',
  'label_chip_home': 'المنزل',
  'label_chip_work': 'العمل',
  'label_chip_other': 'أخرى',

  // ── Errors ──────────────────────────────────────────────
  'error_no_connection': 'لا يوجد اتصال بالإنترنت. تحقق من الشبكة وحاول مرة أخرى.',
  'error_timeout': 'استغرق الطلب وقتاً طويلاً. حاول مرة أخرى.',
  'error_server': 'حدث خطأ لدينا. حاول بعد قليل.',
  'error_not_found': 'لم نعثر على ما تبحث عنه.',
  'error_session_expired': 'انتهت صلاحية الجلسة. سجّل الدخول مرة أخرى.',
  'error_forbidden': 'لا تملك صلاحية الوصول إلى هذا.',
  'error_rate_limited': 'محاولات كثيرة. انتظر قليلاً ثم حاول مرة أخرى.',
  'error_unexpected': 'حدث خطأ ما. حاول مرة أخرى.',
  'error_bad_request': 'تعذّر إتمام الطلب. تحقق من البيانات وحاول مرة أخرى.',
  'error_account_deactivated': 'هذا الحساب معطّل. تواصل مع الدعم للمساعدة.',
  'error_account_not_found': 'لا يوجد حساب بهذه البيانات.',
  'error_address_not_found': 'هذا العنوان لم يعد متاحاً. اختر عنواناً آخر.',
  'error_edfali_account_not_found': 'لا يوجد حساب إدفعلي مسجّل لهذا الرقم.',
  'error_edfali_otp_invalid': 'الرمز غير صحيح. تحقق منه وحاول مرة أخرى.',
  'error_edfali_payment_failed': 'لم تتم عملية الدفع. حاول مرة أخرى أو استخدم طريقة أخرى.',
  'error_edfali_session_expired': 'انتهت جلسة الدفع. ابدأ الطلب من جديد.',
  'error_payout_method_invalid': 'تحقق من بيانات الاستلام وحاول مرة أخرى.',
  'error_refund_active_exists': 'يوجد طلب استرداد مفتوح لهذا الطلب بالفعل.',
  'error_refund_items_required': 'اختر منتجاً واحداً على الأقل للاسترداد.',
  'error_refund_item_invalid': 'أحد المنتجات المختارة غير قابل للاسترداد.',
  'field_invalid_email': 'أدخل بريداً إلكترونياً صحيحاً',
  'field_email_taken': 'هذا البريد الإلكتروني مستخدم في حساب آخر',
  'field_phone_taken': 'رقم الهاتف مستخدم في حساب آخر',
  'field_too_short': 'القيمة قصيرة جداً',
  'field_too_long': 'القيمة طويلة جداً',
  'stock_limit_reached': 'لا يتوفر سوى @count في المخزون',
  'only_n_left': 'بقي @count فقط',
  'vendor_does_not_deliver': 'هذا المتجر لا يوصّل إلى العنوان المحدد. اختر عنواناً آخر، أو اطلب من متجر يغطي منطقتك.',
  'close': 'إغلاق',
  'app_version': 'الإصدار',
};
