const Map<String, String> en = {
  // ── General ─────────────────────────────────────────────
  'app_name': 'Amazonat',
  'ok': 'OK',
  'cancel': 'Cancel',
  'retry': 'Retry',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'search': 'Search',
  'see_all': 'See All',
  'continue_text': 'Continue',
  'loading': 'Loading...',
  'no_data': 'No data available',
  'error': 'Something went wrong',
  'success': 'Success',

  // ── Auth / Login ────────────────────────────────────────
  'login_title': 'Welcome Back',
  'login_subtitle': 'Sign in to continue shopping',
  'phone_number': 'Phone Number',
  'phone_hint': 'Enter your phone number',
  'continue_as_guest': 'Continue as Guest',
  'send_otp': 'Send OTP',
  'or_continue_with': 'Or continue with',
  'continue_with_google': 'Continue with Google',
  'continue_with_apple': 'Continue with Apple',
  'terms_agreement': 'By continuing, you agree to our',
  'terms_of_service': 'Terms of Service',
  'privacy_policy': 'Privacy Policy',
  'and': 'and',

  // ── OTP / Verification ─────────────────────────────────
  'verify_phone_title': 'Verify Phone',
  'verify_phone_subtitle': 'We sent a verification code to your phone',
  'otp_sent_to': 'OTP sent to @phone',
  'enter_otp': 'Enter OTP code',
  'verify_otp': 'Verify',
  'resend_otp': 'Resend Code',
  'resend_in': 'Resend in @seconds s',
  'didnt_receive_code': "Didn't receive the code?",

  // ── Complete Details ────────────────────────────────────
  'complete_details_title': 'Complete Your Profile',
  'complete_details_subtitle': 'Tell us a bit about yourself',
  'full_name': 'Full Name',
  'full_name_hint': 'Enter your full name',
  'email': 'Email',
  'email_hint': 'Enter your email address',
  'create_account': 'Create Account',

  // ── Join Now ────────────────────────────────────────────
  'join_now_title': 'Join Amazonat',
  'join_now_subtitle': 'Discover amazing products from local sellers',
  'get_started': 'Get Started',
  'already_have_account': 'Already have an account?',
  'login': 'Login',

  // ── Home Screen ─────────────────────────────────────────
  'home': 'Home',
  'category': 'Category',
  'popular_products': 'Popular Product',
  'new_collection': 'New Collection',
  'discount_banner': 'Discount 20% for\nnew members',
  'shop_now': 'Shop now',
  'search_products': 'Search Products',
  'view_all': 'View All',

  // ── Product ─────────────────────────────────────────────
  'product_details': 'Product Details',
  'details': 'Details',
  'description': 'Description',
  'reviews': 'Reviews',
  'reviews_and_rating': 'Reviews & Rating',
  'add_to_cart': 'Add To Cart',
  'seller': 'Seller',
  'all_sellers': 'All Sellers',
  'learn_more': 'Learn more',

  // ── Category ────────────────────────────────────────────
  'categories': 'Categories',
  'all_categories': 'All Categories',

  // ── Cart ────────────────────────────────────────────────
  'cart': 'Cart',
  'my_cart': 'My Cart',
  'items': '@count Items',
  'select_all': 'Select All',
  'subtotal': 'Sub_Total',
  'discount': 'Discount',
  'total_cost': 'Total Cost',
  'checkout': 'CheckOut',
  'remove_item': 'Remove Item',
  'empty_cart': 'Your cart is empty',
  'empty_cart_message':
      'Looks like you haven\'t added anything to your cart yet',

  // ── Checkout ────────────────────────────────────────────
  'checkout_title': 'Checkout',
  'delivery_address': 'Delivery Address',
  'payment_method': 'Payment Method',
  'add_card': 'Add Card',
  'place_order': 'Place Order',
  'order_summary': 'Order Summary',
  'add_new_address': 'Add new address',
  'complete_payment': 'Complete Payment',
  'select_address': 'Please select a delivery address',
  'select_payment': 'Please select a payment method',
  'payment_cancelled': 'Payment Cancelled',
  'payment_cancelled_message': 'Your payment was not completed. You can try again.',
  'order_confirmed': 'Order Confirmed!',
  'order_confirmed_message': 'Your order has been placed successfully',
  'order_on_its_way': 'Your order is on its way.',
  'track_my_order': 'Track My Order',
  'continue_shopping': 'Continue Shopping',
  'show_items': 'Show items',
  'hide_items': 'Hide items',
  'generic_error': 'Something went wrong. Please try again.',

  // ── Orders ──────────────────────────────────────────────
  'my_orders': 'My Order',
  'active': 'Active',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'order_details': 'Order Details',
  'track_order': 'Track Order',
  'return_order': 'Return',
  'pickup': 'Pickup',
  'no_orders': 'No orders yet',

  // ── Seller ──────────────────────────────────────────────
  'sellers': 'Sellers',
  'follow': 'Follow',
  'following': 'Following',
  'followers': 'Followers',
  'closed': 'Closed',
  'open': 'Open',

  // ── Account / Profile ───────────────────────────────────
  'my_account': 'My Account',
  'profile': 'Profile',
  'address_book':       'Address Book',
  'pick_address_title': 'Select Delivery Address',
  'delivery_areas': 'Delivery Areas',
  'help_center': 'Help Center',
  'language': 'Language',
  'logout': 'Logout',
  'logout_confirm': 'Are you sure you want to logout?',

  // ── Bottom Nav ──────────────────────────────────────────
  'nav_home': 'Home',
  'nav_category': 'Category',
  'nav_seller': 'Seller',
  'nav_cart': 'Cart',
  'nav_account': 'Account',

  // ── Products List / Filter ────────────────────────────
  'all_products': 'All Products',
  'products_found': '@count Products',
  'filter_title': 'Filter',
  'clear_all': 'Clear All',
  'apply_filters': 'Apply Filters',
  'sort_by': 'Sort By',
  'sort_relevance': 'Relevance',
  'sort_price_low_high': 'Price: Low to High',
  'sort_price_high_low': 'Price: High to Low',
  'sort_rating': 'Highest Rating',
  'price_range': 'Price Range',
  'min_rating': 'Minimum Rating',
  'and_above': '& above',
  'no_products': 'No Products Found',
  'no_products_message': 'Try adjusting your filters or search term',
  'all_filter': 'All',

  // ── Product Details ───────────────────────────────────
  'quantity': 'Quantity',
  'in_stock': 'In Stock',
  'out_of_stock': 'Out of Stock',
  'see_all_reviews': 'See All Reviews',
  'view_all_sellers': 'View All Sellers',
  'share_product': 'Share',
  'added_to_cart': 'Added to cart!',
  'show_less': 'Show less',
  'total_price': 'Total',

  // ── Address Book ────────────────────────────────────────
  'add_address':              'Add Address',
  'edit_address':             'Edit Address',
  'address_label':            'Address Label',
  'full_address_field':       'Full Address',
  'recipient_name':           'Recipient Name',
  'address_line_1':           'Address Line 1',
  'address_line_2':           'Address Line 2',
  'address_line_2_optional':  'Apartment, floor, etc. (optional)',
  'city_field':               'City',
  'state_field':              'State / District',
  'country_field':            'Country',
  'postal_code':              'Postal Code',
  'postal_code_optional':     'Postal code (optional)',
  'set_as_default':           'Set as default address',
  'save_address':             'Save Address',
  'delete_address':           'Delete Address',
  'delete_address_confirm':   'This address will be permanently removed.',
  'address_deleted':          'Address has been deleted.',
  'default_address_set':      'Default address updated',
  'is_now_default':           'is now your default address.',
  'no_addresses':             'No saved addresses',
  'no_addresses_message':     'Add an address to speed up your checkout.',
  'add_first_address':        'Add your first address',
  'default_badge':            'Default',
  'label_required':           'This field is required',
  'address_required':         'Please enter a valid address',
  'deleted':                  'Deleted',

  // ── Validation ──────────────────────────────────────────
  'required_field': 'This field is required',
  'invalid_phone': 'Please enter a valid phone number',
  'invalid_email': 'Please enter a valid email address',
  'invalid_otp': 'Please enter a valid OTP code',
  'name_too_short': 'Name must be at least 2 characters',
};
