const Map<String, String> en = {
  // ── General ─────────────────────────────────────────────
  'app_name': 'Amazonat',
  'ok': 'OK',
  'cancel': 'Cancel',
  'retry': 'Retry',
  'save': 'Save',
  'delete': 'Delete',
  'search': 'Search',
  'see_all': 'See All',
  'continue_text': 'Continue',
  'loading': 'Loading...',
  'no_data': 'No data available',
  'error': 'Something went wrong',
  'success': 'Success',

  // ── Auth / Login ────────────────────────────────────────
  'login_title': 'Welcome Back',
  'login_subtitle': 'Sign in to continue shopping',
  'phone_number': 'Phone Number',
  'phone_hint': 'Enter your phone number',
  'continue_as_guest': 'Continue as Guest',
  'send_otp': 'Send OTP',
  'or_continue_with': 'Or continue with',
  'continue_with_google': 'Continue with Google',
  'continue_with_apple': 'Continue with Apple',
  'terms_agreement': 'By continuing, you agree to our',
  'terms_of_service': 'Terms of Service',
  'privacy_policy': 'Privacy Policy',
  'and': 'and',

  // ── OTP / Verification ─────────────────────────────────
  'verify_phone_title': 'Verify Phone',
  'verify_phone_subtitle': 'We sent a verification code to your phone',
  'otp_sent_to': 'OTP sent to @phone',
  'enter_otp': 'Enter OTP code',
  'verify_otp': 'Verify',
  'resend_otp': 'Resend Code',
  'resend_in': 'Resend in @seconds s',
  'didnt_receive_code': "Didn't receive the code?",
  'edit_phone': 'Change phone number',
  'otp_rate_limited': 'Too many codes requested for this number. Try again later.',
  'otp_too_many_attempts': 'Too many incorrect attempts. Request a new code.',

  // ── Registration ────────────────────────────────────────
  'no_account_found':   'No account found',
  'sign_up_prompt':     'Add a few details to create your account.',
  'sign_up':            'Sign up',
  'first_name_label':   'First name',
  'first_name_hint':    'Sara',
  'last_name_label':    'Last name',
  'last_name_hint':     'Mohamed',
  'last_name_optional': 'Last name (optional)',

  // ── Complete Details ────────────────────────────────────
  'complete_details_title': 'Complete Your Profile',
  'complete_details_subtitle': 'Tell us a bit about yourself',
  'full_name': 'Full Name',
  'full_name_hint': 'Enter your full name',
  'email': 'Email',
  'email_hint': 'Enter your email address',
  'create_account': 'Create Account',

  // ── Join Now ────────────────────────────────────────────
  'join_now_title': 'Join Amazonat',
  'join_now_subtitle': 'Discover amazing products from local sellers',
  'get_started': 'Get Started',
  'already_have_account': 'Already have an account?',
  'login': 'Login',

  // ── Home Screen ─────────────────────────────────────────
  'home': 'Home',
  'category': 'Category',
  'popular_products': 'Popular Product',
  'new_collection': 'New Collection',
  'discount_banner': 'Discount 20% for\nnew members',
  'shop_now': 'Shop now',
  'know_more': 'Know more',
  'search_products': 'Search Products',
  'view_all': 'View All',

  // ── Product ─────────────────────────────────────────────
  'product_details': 'Product Details',
  'details': 'Details',
  'description': 'Description',
  'reviews': 'Reviews',
  'reviews_and_rating': 'Reviews & Rating',
  'add_to_cart': 'Add To Cart',
  'seller': 'Seller',
  'all_sellers': 'All Sellers',
  'learn_more': 'Learn more',

  // ── Category ────────────────────────────────────────────
  'categories': 'Categories',
  'all_categories': 'All Categories',

  // ── Cart ────────────────────────────────────────────────
  'cart': 'Cart',
  'my_cart': 'My Cart',
  'items': '@count Items',
  'select_all': 'Select All',
  'subtotal': 'Subtotal',
  'discount': 'Discount',
  'total_cost': 'Total Cost',
  'checkout': 'CheckOut',
  'remove_item': 'Remove Item',
  'empty_cart': 'Your cart is empty',
  'empty_cart_message':
      'Looks like you haven\'t added anything to your cart yet',

  // ── Checkout ────────────────────────────────────────────
  'checkout_title': 'Checkout',
  'delivery_address': 'Delivery Address',
  'payment_method': 'Payment Method',
  'add_card': 'Add Card',
  'place_order': 'Place Order',
  'order_summary': 'Order Summary',
  'add_new_address': 'Add new address',
  'complete_payment': 'Complete Payment',
  'select_address': 'Please select a delivery address',
  'select_payment': 'Please select a payment method',
  'payment_cancelled': 'Payment not completed',
  'payment_cancelled_message': 'The payment was cancelled and nothing was charged. Your items are still in the cart.',
  'order_confirmed': 'Order received',
  'order_confirmed_message': 'Thank you. The store is preparing your order, and you will be notified at every status change.',
  'order_on_its_way': 'Your order is on its way.',
  'track_my_order': 'Track My Order',
  'continue_shopping': 'Continue Shopping',
  'show_items': 'Show items',
  'hide_items': 'Hide items',
  'generic_error': 'Something went wrong. Please try again.',

  // ── Orders ──────────────────────────────────────────────
  'my_orders': 'My Order',
  'active': 'Active',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'order_details': 'Order Details',
  'track_order': 'Track Order',
  'return_order': 'Return',
  'pickup': 'Pickup',
  'no_orders': 'No orders yet',
  'no_orders_desc': 'Your orders will appear here once you place one.',
  'order_number': 'Order #',
  'view_details': 'View details',
  'order_items': 'Order Items',
  'shipping_fee': 'Shipping Fee',
  'total_amount': 'Total',
  'vendor': 'Seller',
  'shipping_address': 'Shipping Address',
  'cancel_order': 'Cancel Order',
  'cancel_order_confirm': 'Cancel this order? This cannot be undone.',
  'cancel_order_reason_hint': 'Reason (optional)',
  'order_cancelled': 'Order cancelled',
  'order_cancelled_message': 'Your order has been cancelled.',
  'order_placed_on': 'Placed on @date',
  'cancellation_reason': 'Cancellation reason',
  'status_pending': 'Pending',
  'status_paid': 'Paid',
  'status_cod': 'Cash on Delivery',
  'status_processing': 'Processing',
  'status_shipped': 'Shipped',
  'status_ready_for_pickup': 'Ready for Pickup',
  'status_delivered': 'Delivered',
  'status_cancelled': 'Cancelled',
  'status_refunded': 'Refunded',
  'status_unknown': 'Unknown',

  // ── Seller ──────────────────────────────────────────────
  'sellers': 'Sellers',
  'view_store': 'View store',
  'store_products': 'Products',
  'no_store_products': 'This seller has no products yet',
  'search_sellers': 'Search sellers',
  'no_sellers': 'No sellers found',
  'no_sellers_message': 'Try a different search, or check back later.',
  'verified': 'Verified',
  'follow': 'Follow',
  'following': 'Following',
  'followers': 'Followers',
  'closed': 'Closed',
  'open': 'Open',

  // ── Account / Profile ───────────────────────────────────
  'my_account': 'My Account',
  'profile': 'Profile',
  'address_book':       'Address Book',
  'pick_address_title': 'Select Delivery Address',
  'delivery_areas': 'Delivery Areas',
  'help_center': 'Help Center',
  'language': 'Language',
  'arabic': 'Arabic',
  'english': 'English',
  'logout': 'Logout',
  'logout_confirm': 'Are you sure you want to logout?',

  // ── Bottom Nav ──────────────────────────────────────────
  'request_refund': 'Request Refund',
  'refund_type': 'Refund type',
  'refund_type_full': 'Full order',
  'refund_type_partial': 'Some items',
  'refund_reason': 'Reason',
  'refund_reason_hint': 'Select a reason',
  'refund_explanation': 'Tell us what went wrong',
  'select_items': 'Items to refund',
  'select_at_least_one_item': 'Select at least one item',
  'payout_method': 'Payout method',
  'submit_refund': 'Submit request',
  'refund_requested': 'Refund requested',
  'refund_requested_message': 'We will review your request and arrange a pickup.',
  'field_required': 'This field is required',
  'field_invalid': 'Please check this value',
  'refund_tracker': 'Refunds',
  'back': 'Back',
  'refund_label': 'Refund',
  'refund_tracking': 'Refund tracking',
  'refund_track': 'Track',
  'refund_next': 'Next',
  'refund_next_pending': 'The store has your request and will review it shortly.',
  'refund_next_under_review': 'The store is reviewing your request and the items you returned.',
  'refund_next_under_processing': 'We will collect the items at the scheduled time, then release the payout.',
  'refund_next_awaiting_payout': 'The amount is on its way to your payout method.',
  'refund_net_amount': 'Net amount paid out',
  'refund_eligible_lead': 'Something wrong?',
  'refund_eligible_title': 'You can request a refund for this order',
  'refund_eligible_collect': 'We collect the items. You pick a pickup date and address.',
  'refund_eligible_money': 'Then the money moves. To the payout method you choose, less the transport cost.',
  'refund_amount': 'Amount',
  'refund_requested_at': 'Requested',
  'refund_requested_short': 'Requested',
  'refund_completed_at': 'Completed',
  'transport_cost': 'Transport cost',
  'decline_reason': 'Decline reason',
  'payouts': 'Payouts',
  'pickup_schedule': 'Pickup',
  'refund_status_pending': 'Pending',
  'refund_status_under_processing': 'Processing',
  'refund_status_under_review': 'Under review',
  'refund_status_awaiting_payout': 'Awaiting payout',
  'refund_status_rejected': 'Rejected',
  'refund_status_refunded': 'Refunded',
  'payout_status_pending': 'Pending',
  'payout_status_processing': 'Processing',
  'payout_status_approved': 'Approved',
  'payout_status_completed': 'Completed',
  'payout_status_declined': 'Declined',
  'transaction_proof': 'Transfer receipt',
  'transaction_proof_hint': 'Tap to view',
  'save_to_photos': 'Save to Photos',
  'proof_saved': 'Receipt saved to your photos',
  'proof_save_failed': 'Could not save the receipt. Try again.',
  'photos_permission_denied': 'Allow photo access to save the receipt.',
  'edfali_wallet': 'Edfali wallet number',
  'edfali_wallet_hint': '09XXXXXXXX',
  'edfali_confirm_title': 'Confirm payment',
  'edfali_code_sent_to': 'Enter the code sent to @phone',
  'edfali_attempts_remaining': '@count attempts remaining',
  'edfali_otp_invalid': 'Wrong code. Please try again.',
  'edfali_attempts_exceeded': 'Too many wrong codes. The order was cancelled.',
  'edfali_session_expired': 'The payment session expired. Please order again.',
  'edfali_payment_failed': 'The payment failed. Please try another method.',
  'payment_under_review': 'Payment under review',
  'payment_under_review_message': 'We are confirming this payment with the provider. No action is needed.',
  'confirm_payment': 'Confirm payment',
  'single_seller_checkout': 'Select items from one seller at a time to check out.',
  'nav_home': 'Home',
  'nav_category': 'Category',
  'nav_seller': 'Seller',
  'nav_cart': 'Cart',
  'nav_account': 'Account',

  // ── Products List / Filter ────────────────────────────
  'all_products': 'All Products',
  'products_found': '@count Products',
  'filter_title': 'Filter',
  'clear_all': 'Clear All',
  'apply_filters': 'Apply Filters',
  'sort_by': 'Sort By',
  'sort_relevance': 'Relevance',
  'sort_price_low_high': 'Price: Low to High',
  'sort_price_high_low': 'Price: High to Low',
  'sort_rating': 'Highest Rating',
  'sort_name_asc': 'Name: A to Z',
  'search_results_for': 'Results for',
  'active_filters': 'Active filters',
  'search_hint': 'Search products...',
  'price_range': 'Price Range',
  'min_rating': 'Minimum Rating',
  'and_above': '& above',
  'no_products': 'No Products Found',
  'no_products_message': 'Try adjusting your filters or search term',
  'all_filter': 'All',

  // ── Product Details ───────────────────────────────────
  'quantity': 'Quantity',
  'in_stock': 'In Stock',
  'out_of_stock': 'Out of Stock',
  'see_all_reviews': 'See All Reviews',
  'view_all_sellers': 'View All Sellers',
  'share_product': 'Share',
  'added_to_cart': 'Added to cart!',
  'show_less': 'Show less',
  'total_price': 'Total',

  // ── Address Book ────────────────────────────────────────
  'add_address':              'Add Address',
  'address_label':            'Address Label',
  'full_address_field':       'Full Address',
  'recipient_name':           'Recipient Name',
  'address_line_1':           'Address Line 1',
  'address_line_2':           'Address Line 2',
  'address_line_2_optional':  'Apartment, floor, etc. (optional)',
  'city_field':               'City',
  'state_field':              'State / District',
  'country_field':            'Country',
  'postal_code':              'Postal Code',
  'postal_code_optional':     'Postal code (optional)',
  'set_as_default':           'Set as default address',
  'save_address':             'Save Address',
  'delete_address':           'Delete Address',
  'delete_address_confirm':   'This address will be permanently removed.',
  'address_deleted':          'Address has been deleted.',
  'default_address_set':      'Default address updated',
  'is_now_default':           'is now your default address.',
  'no_addresses':             'No saved addresses',
  'no_addresses_message':     'Add an address to speed up your checkout.',
  'add_first_address':        'Add your first address',
  'default_badge':            'Default',
  'label_required':           'This field is required',
  'address_required':         'Please enter a valid address',
  'deleted':                  'Deleted',

  // ── Notifications ───────────────────────────────────────
  'notifications':                 'Notifications',
  'notifications_description':     'View and manage your notifications.',
  'notifications_all':             'All',
  'notifications_unread':          'Unread',
  'notifications_read':            'Read',
  'mark_read':                     'Mark as read',
  'mark_all_read':                 'Mark all as read',
  'no_notifications':              'No notifications',
  'no_notifications_message':      "You're all caught up. New notifications will appear here.",
  'all_notifications_marked_read': 'All notifications marked as read',

  // ── Relative Time ───────────────────────────────────────
  'time_just_now':    'Just now',
  'time_minutes_ago': '@count min ago',
  'time_hours_ago':   '@count h ago',
  'time_days_ago':    '@count d ago',
  'time_weeks_ago':   '@count w ago',
  'time_months_ago':  '@count mo ago',
  'time_years_ago':   '@count y ago',

  // ── Validation ──────────────────────────────────────────
  'required_field': 'This field is required',
  'invalid_phone': 'Please enter a valid phone number',
  'invalid_email': 'Please enter a valid email address',
  'invalid_otp': 'Please enter a valid OTP code',
  'name_too_short': 'Name must be at least 2 characters',
  'new_arrivals': 'New Arrivals',
  'featured_stores': 'Featured Stores',
  'all_categories_filter': 'All',
  'search_home_hint': 'Search products, stores…',
  'appearance': 'Appearance',
  'theme_light': 'Light',
  'theme_dark': 'Dark',
  'theme_system': 'System',
  'home_hero_title': 'Handmade in Libya',
  'order_progress': 'Progress',
  'step_placed': 'Placed',
  'step_paid': 'Paid',
  'step_shipped': 'Shipped',
  'step_delivered': 'Delivered',
  'total_paid': 'Total paid',
  'sold_shipped_by': 'Sold and shipped by this store',
  'orders_count': '@count orders',
  'orders_on_the_way': '@count on the way',
  'items_count': '@count items',
  'items_count_one': '@count item',
  'sellers_subtitle': 'Libyan makers selling straight from the workshop',
  'chat_on_whatsapp': 'Chat on WhatsApp',
  'clear_search': 'Clear search',
  'loading_more_sellers': 'Loading more stores…',
  'products_label': 'Products',
  'group_today': 'Today',
  'group_yesterday': 'Yesterday',
  'group_earlier': 'Earlier',
  'unread_of_total': '@unread unread of @total notifications',
  'view_order_action': 'View order',
  'cart_total': 'Cart total',
  'cart_stores_note': 'Each store is paid for separately; shipping is calculated inside that store’s checkout.',
  'cart_items_from': '@items from @stores',
  'you_saved': 'You saved',
  'paying_store': 'Paying',
  'stores_count': '@count stores',
  'stores_count_one': '1 store',
  'best_sellers': 'Best sellers',
  'admin_picks': 'Admin picks',
  'read_more': 'Read more',
  'read_less': 'Read less',
  'weight_label': 'Weight',
  'sku_label': 'SKU',
  'added_label': 'Added',
  'more_from_store': 'More from this store',
  'available_now_store': 'Available now from this store',
  'not_available_order': 'Not available to order',
  'currently_unavailable': 'Currently unavailable',
  'out_of_stock_note': 'This product cannot be ordered right now. Browse the rest of the store, or check back later.',
  'product_not_found': 'Product not found',
  'product_not_found_body': 'This product may no longer be available, or the seller has removed it from their store.',
  'browse_products': 'Browse products',
  'loading_product': 'Loading product…',
  'pay_edfali_hint': 'A confirmation code arrives by SMS',
  'pay_cod_hint': 'Pay in cash when the order arrives',
  'pay_gateway_hint': 'You will be taken to the payment page',
  'shipping_pending': 'Calculated after address',
  'amount_paid': 'Amount paid',
  'amount_label': 'Amount',
  'status_label': 'Status',
  'back_to_cart': 'Back to cart',
  'edfali_lead': 'Edfali sent a confirmation code to @phone. Enter it to complete the payment.',
  'code_expires_in': 'Code expires in',
  'edfali_hold_warn': 'Keep this screen open until you confirm — the order is held, and is cancelled automatically if the code expires.',
  'edfali_no_resend': 'Once confirmed, the store starts preparing your order and you are notified at every status change. There is no resend service — if the code expires, order again from your cart.',
  'price_from': 'From',
  'price_to': 'To',
  'search_the_market': 'Search the market',
  'search_subtitle': 'Handmade goods from Libyan stores',
  'recent_searches': 'Recent searches',
  'shop_by': 'Shop by',
  'browse_categories': 'Browse categories',
  'subcategories_count': '@count subcategories',
  'no_subcategories': 'No subcategories',
  'pull_to_refresh': 'Pull to refresh',
  'clear_filters': 'Clear filters',
  'loading_more': 'Loading more…',
  'categories_title': 'Categories',
  'categories_subtitle': 'Every craft on the marketplace',
  'all_products_title': 'All products',
  'search_hint_short': 'Search products…',
  'splash_tagline': "Libya's handmade marketplace — maker's hand to your door",
  'made_in_libya': 'Made in Libya',
  'onboard_1_title': 'Straight from the workshop',
  'onboard_1_body': 'Every piece is sold by the Libyan maker who made it — no middleman between their bench and your door.',
  'onboard_2_title': 'Pay the way you like',
  'onboard_2_body': 'Confirm with an Edfali code, or pay in cash when the order arrives.',
  'onboard_3_title': 'Follow it all the way',
  'onboard_3_body': 'Track every order from the workshop to your city, and get a notification at each step.',
  'skip': 'Skip',
  'next': 'Next',
  'start_shopping': 'Start shopping',
  'welcome_title': 'Welcome to Amazonat',
  'welcome_subtitle': 'Sign in with your phone number to start shopping.',
  'trust_payment': 'Edfali or cash on delivery',
  'trust_stores': 'Verified Libyan stores',
  'trust_delivery': 'Delivery to every city',
  'sms_language': 'Language of the code message',
  'first_time_note': 'First time here? We will ask for your name and email before sending the code.',
  'step_enter_phone': 'Enter your phone number',
  'step_enter_code': 'Enter the code we send you',
  'optional_chip': 'Optional',
  'create_account_subtitle': 'We need these before we can send your code.',
  'code_sent_to_phone': 'We sent a code to @phone',
  'map_location': 'Map location',
  'map_pin_hint': 'Move the map so the pin sits on your door, then confirm.',
  'confirm_location': 'Confirm this location',
  'change_location': 'Change',
  'location_required': 'Please select your location on the map',
  'location_pinned': 'Location pinned',
  'map_moving': 'Moving the map…',
  'map_moving_hint': 'Lift your finger to read the address under the pin',
  'resolving_address': 'Finding the address…',
  'no_street_address': 'No street address here',
  'no_street_address_hint':
      'We will save the exact coordinates — the courier still navigates to the pin.',
  'coordinates': 'Saved coordinates',
  'coordinates_live': 'Updates as the map moves',
  'location_services_off':
      'Location is off, so we cannot jump to where you are. Pin your door by hand, or',
  'location_permission_denied':
      'Location access is denied, so we cannot jump to where you are. Pin your door by hand, or',
  'open_settings': 'open settings',
  'my_location': 'My location',
  'invalid_libyan_phone': 'Enter a valid Libyan number (9 digits)',
  'select_city': 'Select city',
  'search_city': 'Search cities',
  'district_optional': 'District (optional)',
  'fix_fields': 'Fix @count fields',
  'section_shopping': 'Shopping',
  'section_preferences': 'Preferences',
  'section_account': 'Account',
  'stat_orders': 'Orders',
  'stat_addresses': 'Addresses',
  'stat_unread': 'Unread',
  'default_address': 'Default address',
  'my_addresses': 'My addresses',
  'addresses_subtitle': 'Where your orders are delivered',
  'refund_type_full_hint': 'Return everything in this order',
  'refund_type_partial_hint': 'Pick what you are returning',
  'refund_which_items': 'Which items',
  'refund_reason_pick': 'Reason',
  'refund_reason_pick_hint': 'Choose a reason',
  'refund_tell_us': 'Tell us what happened',
  'refund_tell_us_hint': 'Describe the problem in a sentence or two',
  'refund_payout_method': 'Where should we send the money',
  'refund_review': 'Review',
  'refund_estimate': 'Estimated refund',
  'refund_estimate_note': 'An estimate. Transport cost is deducted by the store after review, so the amount that lands may be lower.',
  'refund_step_1': 'Items and reason',
  'refund_step_2': 'Payout',
  'refund_continue': 'Continue',
  'refund_submit': 'Submit request',
  'refund_no_payout_methods': 'No payout methods are available right now. Try again later.',
  'refund_items_count': '@count of @total items',
  'label_chip_home': 'Home',
  'label_chip_work': 'Work',
  'label_chip_other': 'Other',

  // ── Errors ──────────────────────────────────────────────
  'error_no_connection': 'No internet connection. Check your network and try again.',
  'error_timeout': 'The request took too long. Try again.',
  'error_server': 'Something went wrong on our side. Try again in a moment.',
  'error_not_found': 'We could not find what you were looking for.',
  'error_session_expired': 'Your session has expired. Please sign in again.',
  'error_forbidden': 'You do not have access to this.',
  'error_rate_limited': 'Too many attempts. Wait a moment and try again.',
  'error_unexpected': 'Something went wrong. Try again.',
  'error_bad_request': 'That request could not be completed. Check your details and try again.',
  'error_account_deactivated': 'This account has been deactivated. Contact support for help.',
  'error_account_not_found': 'No account matches these details.',
  'error_address_not_found': 'That address is no longer available. Pick another one.',
  'error_edfali_account_not_found': 'No Edfali account is registered for this number.',
  'error_edfali_otp_invalid': 'That code is not correct. Check it and try again.',
  'error_edfali_payment_failed': 'The payment did not go through. Try again or use another method.',
  'error_edfali_session_expired': 'The payment session expired. Start the order again.',
  'error_payout_method_invalid': 'Check the payout details and try again.',
  'error_refund_active_exists': 'A refund request for this order is already open.',
  'error_refund_items_required': 'Select at least one item to refund.',
  'error_refund_item_invalid': 'One of the selected items cannot be refunded.',
  'field_invalid_email': 'Enter a valid email address',
  'field_email_taken': 'This email is already used by another account',
  'field_phone_taken': 'This phone number is already used by another account',
  'field_too_short': 'This is too short',
  'field_too_long': 'This is too long',
  'stock_limit_reached': 'Only @count left in stock',
  'only_n_left': 'Only @count left',
  'vendor_does_not_deliver': 'This store does not deliver to the selected address. Pick another address, or order from a store that covers your area.',
  'close': 'Close',
  'app_version': 'Version',
};
